TrainingArguments:
  encoder_units_1_range: [32, 64, 128]
  encoder_units_2_range: [16, 32, 64]
  learning_rate_range: [0.001, 0.01, 0.1]
  batch_size_range: [16, 32, 64]
  epochs_range: [1, 1, 1]
  max_trials: 1
  executions_per_trial: 1
  training_epochs: 1
  training_validation_split: 0.2
  training_batch_size: 32
  num_trials: 1
  early_stopping_patience: 10
  restore_best_weights: true
  final_epochs: 1
  final_batch_size: 10
  final_validation_split: 0.10
