artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/enendufrankc/Datasets/raw/main/dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["All_vib"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/data_training.csv
  model_ckpt: artifacts/model_trainer/model_ckpt

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/data_training.csv
  model_path: artifacts/model_trainer/anomaly_detector_model.keras
  scaler_path: artifacts/model_trainer/scaler_data.joblib
  metric_file_name: artifacts/model_evaluation/metric.csv